### ISSUE TITLE
JavaScript style guide

### ISSUE THREAD

**Issue by plusreed** [crybapp/library#1]
We should have some sort of JavaScript style guide for Cryb so we can make sure things stay consistent.

We could make our own ESLint configuration of sorts to use, or we could use Prettier and make our own configuration for that as well.

/cc @williamsthing would this be a good idea?

**Comment by NurMarvin** [comment]
Or we could use both.
Sounds good considering we had commits mainly dedicated towards unifying the JavaScript style guide.

**Comment by cfanoulis** [comment]
As a friendly suggestion, please don't use bloody prettier. The style it enforces is barely readable. It's way more efficient to spend 30 mins of your time to create style that's above all, suited to you

**Comment by plusreed** [comment]
If anyone wants to chime in with any suggestions for code style enforcement tools, we'd be happy to hear them :+1: Prettier was just an option that came to my head and I'm definitely open to hearing any suggestions for tools to use.

Another thing that came to mind is an `.editorconfig`.

**Comment by Dirkadin** [comment]
[I'm personally a fan of Google's style](https://google.github.io/styleguide/jsguide.html), but I know that's not for everyone.  Perhaps when a CI/CD pipeline comes online a first step would be to run a predefined linter with something like [Checkstyle](https://github.com/checkstyle/checkstyle)?

**Comment by plusreed** [comment]
The Google style guide seems like it could work! I believe Checkstyle is only for pure Java code, though, so I'm not sure if we could use it.

**Comment by cfanoulis** [comment]
You're looking for eslint (https://npmjs.com/package/eslint), and a
travisci setup to check it.

I can do this if you want, just let me know

**Comment by darnfish** [comment]
Our style essentially boils down to:

```js
const name = 'William'
// Use const when the variable isn't mutable
// Use single quotes instead of double
// No semicolons unless required

// Use the === operand for comparing values
// Always have the brackets up against the statement and away from the curly braces
if(name === 'William') {
    const age = 17
} else if(name === 'Reed')
    console.log('You smell.') // Don't use brackets if they're not needed
else return

// Sort imports by package, models, schemas, interfaces and then utils. Also sort by line width
import fs from 'fs'

import User from './models/user'

import IUser from './models/user/defs'
import StoredUser from './schemas/user.schema'

import { extractUserId } from './utils/helpers.utils'
```

**Comment by plusreed** [comment]
> } else if(name === 'Reed')
> console.log('You smell.') // Don't use brackets if they're not needed

Thank you William for the input but I shower daily

But seriously, I think this could be a good starting point for a code style. We can work on a markdown document with this in it, then we can work on configuration files

**Comment by plusreed** [comment]
This is being worked on in this branch: [`code-style`](https://github.com/crybapp/library/tree/code-style).

If anyone still has any suggestions for code style enforcement tools we're still open to hear your suggestions. :+1:

**Comment by plusreed** [comment]
Hey everyone that is following this! :wave:

So I've added a basic ESLint configuration file in https://github.com/crybapp/library/pull/2/commits/8481d5dcbdf2ff7286bdeffc9dec439c8e733269.

I haven't written ESLint configuration files in a while so I would appreciate any suggestions/feedback if I borked something ^^ I may have missed something as well, so anything helps!

**Comment by plusreed** [comment]
Forgot to say, the PR (#2) for this issue left the draft stage! We're still working on code style guidelines, but we should expect this to be merged soon. :+1:
